### ISSUE TITLE
test digitizer naming fails

### ISSUE THREAD

**Issue by laroque** [project8/mantis#37]
for example:

22:24:17 [ERROR] er/mt_factory.hh(102): Did not find factory for <a_test>.
22:24:17 [ERROR] evice_manager.cc(125): Could not create digitizer <a_test>; aborting
22:24:17 [ERROR] evice_manager.cc(94): Unable to set device
22:24:17 [ERROR] server_worker.cc(71): Unable to configure device manager

**Comment by nsoblath** [comment]
Fixed in commit 975cf1a.
