### ISSUE TITLE
Implement OP_CONFIG for setting/getting acquisition configuration values

### ISSUE THREAD

**Issue by nsoblath** [project8/mantis#54]
Basic Plan
--------------

Any getter and setter operations that involve the acquisition config (and the server config) should be switch to OP_CONFIG.  Whether the operation is a getter or a setter will depend on whether there is information provided in the payload.  If information is provided in the payload, it's a setter operation, and if not, it's a getter operation.

Proposed Changes
-------------------------

Some current OP_GET requests are converted to OP_CONFIG:
* `acq-config`
* `server-config`

Single-configuration-value getter operation will also be accommodated.

Current OP_SET requests are converted to OP_CONFIG.

Current OP_CMD requests are converted to OP_CONFIG:
* `replace-config` (renamed `acq-config` to match the getter version)

Single-Configuration-Value Operations
----------------------------------------------------

If the routing-key specifier (RKS) does not match any of the special RKSs for OP_CONFIG, we will assume that the RKS is indicating a particular configuration value.  Both getter and setter operations will be handled (whereas now only setter operations are handled):

* Setter operations will be handled in the same way they are handled now: the RKS is parsed into a hierarchical param object, and the value is tacked onto the last hierarchical element.  That will then be merged with the acquisition configuration, effecting a setter operation for that single configuration value.

* Getter operations will require a little more work: the RKS is parsed into a hierarchical param object, and then the hierarchy is used to trace a path in the acquisition config, down to the value of interest.  If the requested hierarchy doesn't match the acquisition config, an error is returned.  If the lowest level of the hierarchy doesn't result in a value in the acquisition config, the node or array that it ends in can be returned.

API Consequences
--------------------------

These changes represent a significant non-backwards-compatible change to the API.  Therefore this change is aimed for Mantis 4.x.

Deprecated backwards compatibility can be maintained for a limited time.

Related Issues
--------------------

#48 will be satisfied by this change, and will therefore be closed.

**Comment by laroque** [comment]
Per some discussion, we may instead deprecate the OP_CONFIG operation in favor of get/set operation and using routing_keys to specify parameters. We can discuss further to determine if OP_CONFIG actually offers capability that isn't well expressed by a reasonable combination of OP_GET and OP_SET.

There are two motivations for this:
1) It is currently not always obvious when to use get/set vs config, the distinction seems arbitrary
2) OP_CONFIG is the msgop value which is conditionally locked-out; this change would mean that ever OP_* value would either be always lockable, or never lockable.

**Comment by nsoblath** [comment]
This has been marked "Won't Fix" in light of the planned wire protocol version 1.5.x, which will have OP_CONFIG deprecated, as Ben mentioned.
