### ISSUE TITLE
on linux, mantis_server's exe name is not properly formatted (mangling json messages)

### ISSUE THREAD

**Issue by laroque** [project8/mantis#55]
## Reproduction
build and run the mantis_server on a linux system
submit a run and try to decode the resultant ReplyMessage of an OP_RUN using an assumption of 'utf8' string encoding (such as using dripline_agent or message_monitor)

## Core problem
In mt_version.cc, readlink is used to get the string for the full-path to the exe used. That command does not null terminate the resulting string buffer, which results in mantis constructing a bad json string.

Suggested fix is here:
https://www.securecoding.cert.org/confluence/display/c/POS30-C.+Use+the+readlink%28%29+function+properly

**Comment by nsoblath** [comment]
Fixed by Ben
