### ISSUE TITLE
It would be nice if the CLI were able to expand paths

### ISSUE THREAD

**Issue by laroque** [project8/mantis#59]
My particular use case is that it would be nice to do something like `mantis_server config=~/test_configs/my_server_config.json` from within the build directory while building/testing.

Since the param=value syntax prevents the shell from expanding the `~`, it would be nice if the argument parser would expand known path objects.

**Comment by nsoblath** [comment]
This capability will be implemented in scarab::param_value.

https://github.com/project8/scarab/issues/2

**Comment by nsoblath** [comment]
I spoke too soon.  Scarab::param_values can now be interpreted as paths.  The use of this has to be implemented in mantis to make it useful.

**Comment by nsoblath** [comment]
Ok, now it's done (commit 68432b6)
